[build]
  command = "pnpm build"
  functions = "dist"
  publish = "client/dist"

[dev]
  command = "pnpm dev"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
